//
//  Constants.swift
//  preferrd
//
//  Created by Christianto Budisaputra on 06/06/21.
//

import Foundation

struct Constants {

  static let colors = [
    Color(name: "Aero Blue", hex: "#B6FCDB", relatedTags: [.fresh]),
    Color(name: "Alabaster", hex: "#F9F9F9", relatedTags: [.masculine, .elegant, .modern, .adventurous]),
//    Color(name: "Almond", hex: "#EDD1CB", relatedTags: [.feminine]),
    Color(name: "Anzac", hex: "#DE9E48", relatedTags: [.elegant, .feminine]),
    Color(name: "Apricot Peach", hex: "#FBC2B2", relatedTags: [.fresh]),
    Color(name: "Ash", hex: "#C8C3B4", relatedTags: [.vintage]),
    Color(name: "Astral", hex: "#328CA9", relatedTags: [.masculine]),
//    Color(name: "Athens Gray", hex: "#EFEFF1", relatedTags: [.feminine]),
    Color(name: "Atlantis", hex: "#A2C523", relatedTags: [.nature]),
    Color(name: "Bali Hai", hex: "#839AAB", relatedTags: [.nature]),
//    Color(name: "Banana Mania", hex: "#FCDEB6", relatedTags: [.fresh]),
//    Color(name: "Barely Corn", hex: "#A08C5B", relatedTags: [.elegant]),
    Color(name: "Bermuda", hex: "#77DAD5", relatedTags: [.happy]),
    Color(name: "Big Stone", hex: "#14343F", relatedTags: [.adventurous, .nature]),
//    Color(name: "Big Stone", hex: "#132232", relatedTags: [.nature]),
    Color(name: "Biscay", hex: "#194260", relatedTags: [.masculine]),
    Color(name: "Bitter Lemon", hex: "#DEDE0E", relatedTags: [.happy]),
    Color(name: "Bizzare", hex: "#EDDCD9", relatedTags: [.feminine]),
    Color(name: "Black Pearl", hex: "#051821", relatedTags: [.modern]),
    Color(name: "Blue Bayoux", hex: "#4B6071", relatedTags: [.nature]),
//    Color(name: "Blue Dianne", hex: "#1C3948", relatedTags: [.adventurous]),
    Color(name: "Blue Dianne", hex: "#1A4645", relatedTags: [.modern]),
    Color(name: "Blue Smoke", hex: "#739086", relatedTags: [.modern, .vintage]),
    Color(name: "Blue Whale", hex: "#023246", relatedTags: [.modern]),
    Color(name: "Blue Zodiac", hex: "#102446", relatedTags: [.masculine]),
//    Color(name: "Bone", hex: "#E6DAC7", relatedTags: [.masculine]),
    Color(name: "Bright Gray", hex: "#35364B", relatedTags: [.relaxing]),
    Color(name: "Bright Turquoise", hex: "#3BE3F7", relatedTags: [.fresh]),
//    Color(name: "Burnt Sienna", hex: "#ED6A40", relatedTags: [.vintage]),
//    Color(name: "Cadet Blue", hex: "#A7BAC6", relatedTags: [.adventurous]),
    Color(name: "Cadet Blue", hex: "#A0B3C1", relatedTags: [.masculine, .adventurous]),
    Color(name: "Calypso", hex: "#2F5D8C", relatedTags: [.masculine]),
    Color(name: "Cameo", hex: "#DDB7AB", relatedTags: [.feminine, .modern, .elegant, .adventurous]),
    Color(name: "Camouflage", hex: "#434310", relatedTags: [.nature, .adventurous]),
//    Color(name: "Cararra", hex: "#EFF0EB", relatedTags: [.modern]),
    Color(name: "Carnation", hex: "#F95950", relatedTags: [.feminine, .happy]),
    Color(name: "Casal", hex: "#266867", relatedTags: [.modern]),
//    Color(name: "Cascade", hex: "#8FB0A9", relatedTags: [.vintage]),
//    Color(name: "Chalky", hex: "#EFD78D", relatedTags: [.vintage]),
    Color(name: "Champagne", hex: "#F9E8CE", relatedTags: [.elegant, .vintage, .relaxing, .fresh, .masculine]),
//    Color(name: "Clam Shell", hex: "#D5B9B1", relatedTags: [.modern]),
    Color(name: "Cloud", hex: "#C5C1BB", relatedTags: [.modern]),
    Color(name: "Cocoa Bean", hex: "#40171D", relatedTags: [.nature]),
    Color(name: "Coconut Cream", hex: "#F6F7D7", relatedTags: [.happy, .feminine, .elegant]),
    Color(name: "Comet", hex: "#5A5F77", relatedTags: [.relaxing]),
//    Color(name: "Congress Blue", hex: "#03439B", relatedTags: [.fresh]),
    Color(name: "Corduroy", hex: "#65786A", relatedTags: [.vintage, .masculine]),
//    Color(name: "Corduroy", hex: "#5A6868", relatedTags: [.masculine]),
    Color(name: "Cranberry", hex: "#DE5499", relatedTags: [.feminine]),
//    Color(name: "Cream Can", hex: "#F2D266", relatedTags: [.vintage]),
//    Color(name: "Dairy Cream", hex: "#F9E0BE", relatedTags: [.relaxing]),
    Color(name: "Denim", hex: "#0E6EA9", relatedTags: [.masculine]),
//    Color(name: "Di Serria", hex: "#DD9964", relatedTags: [.relaxing]),
    Color(name: "Dingley", hex: "#6B7D3F", relatedTags: [.nature]),
    Color(name: "Double Spanish White", hex: "#E9DBBD", relatedTags: [.elegant]),
    Color(name: "Downriver", hex: "#0A2C47", relatedTags: [.masculine]),
    Color(name: "Downy", hex: "#6FD3B9", relatedTags: [.relaxing]),
//    Color(name: "Driftwood", hex: "#AD974F", relatedTags: [.elegant]),
    Color(name: "Driftwood", hex: "#9B8148", relatedTags: [.masculine, .elegant]),
//    Color(name: "Ebb", hex: "#EAE7E4", relatedTags: [.adventurous]),
    Color(name: "Ebony Clay", hex: "#232D3B", relatedTags: [.happy]),
    Color(name: "Edward", hex: "#A7BBAC", relatedTags: [.nature]),
    Color(name: "Eggplant", hex: "#563C50", relatedTags: [.feminine]),
    Color(name: "Faded Jade", hex: "#457373", relatedTags: [.modern, .masculine]),
    Color(name: "Finch", hex: "#556144", relatedTags: [.nature]),
    Color(name: "Finn", hex: "#723147", relatedTags: [.feminine]),
    Color(name: "Flame Pea", hex: "#D76735", relatedTags: [.vintage]),
//    Color(name: "Flamingo", hex: "#F15A42", relatedTags: [.happy]),
//    Color(name: "Flesh", hex: "#FFCBA3", relatedTags: [.relaxing, .fresh]),
    Color(name: "Fountaine Blue", hex: "#64A6C4", relatedTags: [.relaxing]),
    Color(name: "French Pass", hex: "#ADF1FB", relatedTags: [.fresh]),
    Color(name: "Froly", hex: "#F96E91", relatedTags: [.happy]),
    Color(name: "Fruit Salad", hex: "#4C8C64", relatedTags: [.adventurous]),
//    Color(name: "Gallery", hex: "#EAEAEA", relatedTags: [.elegant]),
//    Color(name: "Gimblet", hex: "#C1A673", relatedTags: [.nature]),
//    Color(name: "Gossip", hex: "#AAF8A5", relatedTags: [.fresh]),
//    Color(name: "Gurkha", hex: "#989481", relatedTags: [.adventurous]),
    Color(name: "Hacienda", hex: "#906B16", relatedTags: [.nature]),
//    Color(name: "Ice Cold", hex: "#A5F8D1", relatedTags: [.fresh]),
//    Color(name: "Illusion", hex: "#F7B0BE", relatedTags: [.happy]),
    Color(name: "Jacksons Purple", hex: "#193382", relatedTags: [.masculine]),
    Color(name: "Jelly Bean", hex: "#287094", relatedTags: [.modern]),
    Color(name: "Jungle Mist", hex: "#AAC9CE", relatedTags: [.feminine, .modern]),
    Color(name: "Juniper", hex: "#769898", relatedTags: [.elegant]),
    Color(name: "Kabul", hex: "#64493D", relatedTags: [.masculine, .nature]),
    Color(name: "Kimberly", hex: "#8474A1", relatedTags: [.feminine]),
    Color(name: "Kournikova", hex: "#FFE877", relatedTags: [.happy]),
    Color(name: "Lavender Pink", hex: "#FBADBE", relatedTags: [.fresh, .happy]),
    Color(name: "Leather", hex: "#A07959", relatedTags: [.vintage, .nature]),
//    Color(name: "Leather", hex: "#937452", relatedTags: [.nature]),
    Color(name: "Lemon", hex: "#FDE910", relatedTags: [.fresh]),
    Color(name: "Lemon Grass", hex: "#999B84", relatedTags: [.feminine]),
    Color(name: "Light Orchid", hex: "#EDB8E8", relatedTags: [.happy]),
//    Color(name: "Lighting Yellow", hex: "#F8BC24", relatedTags: [.modern]),
    Color(name: "Lightning Yellow", hex: "#FAC92C", relatedTags: [.happy, .modern]),
    Color(name: "Lily", hex: "#D1AFC7", relatedTags: [.feminine]),
    Color(name: "Lochmara", hex: "#0181BB", relatedTags: [.happy]),
    Color(name: "Maize", hex: "#F6DAAC", relatedTags: [.relaxing]),
    Color(name: "Manatee", hex: "#8B8D98", relatedTags: [.relaxing]),
//    Color(name: "Matisse", hex: "#1B4793", relatedTags: [.happy]),
    Color(name: "Mint Green", hex: "#A4F9A4", relatedTags: [.fresh]),
    Color(name: "Mischka", hex: "#D9DBE7", relatedTags: [.elegant]),
    Color(name: "Mongoose", hex: "#B5AD75", relatedTags: [.adventurous]),
//    Color(name: "My Pink", hex: "#D49F91", relatedTags: [.elegant]),
    Color(name: "Nandor", hex: "#484E4A", relatedTags: [.modern]),
    Color(name: "Natural Gray", hex: "#898886", relatedTags: [.vintage, .modern, .adventurous]),
//    Color(name: "Niagara", hex: "#0AAFB1", relatedTags: [.adventurous]),
//    Color(name: "Nutmeg", hex: "#7D4427", relatedTags: [.nature]),
    Color(name: "Old Copper", hex: "#665329", relatedTags: [.nature]),
    Color(name: "Copper", hex: "#7C4935", relatedTags: [.masculine, .nature, .vintage]),
//    Color(name: "Orange Peel", hex: "#FF9A00", relatedTags: [.happy]),
    Color(name: "Outer Space", hex: "#1F2829", relatedTags: [.adventurous]),
    Color(name: "Oyster Pink", hex: "#EACACB", relatedTags: [.feminine]),
    Color(name: "Pale Sky", hex: "#666E7F", relatedTags: [.adventurous]),
    Color(name: "Peanut", hex: "#782D16", relatedTags: [.vintage]),
    Color(name: "Persian Green", hex: "#00A099", relatedTags: [.modern, .adventurous]),
    Color(name: "Pickled Bluewood", hex: "#2B4448", relatedTags: [.vintage, .masculine, .modern]),
    Color(name: "Pig Pink", hex: "#FCD4DB", relatedTags: [.relaxing]),
    Color(name: "Plantation", hex: "#264143", relatedTags: [.feminine]),
    Color(name: "Polo Blue", hex: "#8297CC", relatedTags: [.adventurous]),
    Color(name: "Pomegranate", hex: "#EF3C23", relatedTags: [.happy]),
    Color(name: "Porsche", hex: "#EBA56F", relatedTags: [.relaxing]),
//    Color(name: "Pot Pourri", hex: "#EFD9D1", relatedTags: [.feminine]),
    Color(name: "Quicksand", hex: "#BDA28D", relatedTags: [.elegant]),
//    Color(name: "Quill Gray", hex: "#D4D4CE", relatedTags: [.modern]),
    Color(name: "Quill Gray", hex: "#D8D8D6", relatedTags: [.masculine, .modern]),
    Color(name: "Radical Red", hex: "#FF165D", relatedTags: [.happy]),
    Color(name: "Rangitoto", hex: "#303027", relatedTags: [.nature]),
    Color(name: "Congress Blue", hex: "#D55E2S", relatedTags: [.masculine, .fresh]),
    Color(name: "Rolling Stone", hex: "#758086", relatedTags: [.vintage]),
    Color(name: "Ronchi", hex: "#EACB48", relatedTags: [.modern, .vintage]),
    Color(name: "Rose", hex: "#FAAFA8", relatedTags: [.fresh]),
    Color(name: "Rose Bud", hex: "#FBC1A7", relatedTags: [.relaxing, .vintage, .fresh, .feminine]),
//    Color(name: "Rose Bud", hex: "#FCB7A8", relatedTags: [.vintage]),
    Color(name: "Sadle", hex: "#563727", relatedTags: [.elegant]),
    Color(name: "Sandal", hex: "#A38C6D", relatedTags: [.adventurous]),
//    Color(name: "Sanguine Brown", hex: "#874338", relatedTags: [.vintage]),
    Color(name: "Sapphire", hex: "#2C4EA3", relatedTags: [.masculine, .happy]),
    Color(name: "Scooter", hex: "#3EC1D3", relatedTags: [.happy]),
    Color(name: "Shadow", hex: "#7A6B45", relatedTags: [.adventurous]),
//    Color(name: "Side Car", hex: "#F2D8B3", relatedTags: [.vintage]),
    Color(name: "Snowy Mint", hex: "#DDFEDD", relatedTags: [.fresh, .happy]),
//    Color(name: "Soft Peach", hex: "#F4EEED", relatedTags: [.feminine]),
    Color(name: "Sorrel Brown", hex: "#CBB682", relatedTags: [.elegant, .nature, .vintage]),
//    Color(name: "Surf Crest", hex: "#CFE5CC", relatedTags: [.happy]),
    Color(name: "Sushi", hex: "#9CB446", relatedTags: [.nature]),
//    Color(name: "Sycamore", hex: "#877E41", relatedTags: [.adventurous]),
    Color(name: "Sycamore", hex: "#8E793E", relatedTags: [.elegant, .adventurous]),
//    Color(name: "Tacao", hex: "#F1B793", relatedTags: [.fresh]),
//    Color(name: "Tan", hex: "#D0A991", relatedTags: [.adventurous]),
    Color(name: "Tangerine", hex: "#F58800", relatedTags: [.modern, .fresh, .happy]),
    Color(name: "Tango", hex: "#E97E2E", relatedTags: [.vintage]),
    Color(name: "Taupe", hex: "#3D3B2C", relatedTags: [.nature]),
    Color(name: "Texas", hex: "#F8F2A5", relatedTags: [.fresh]),
//    Color(name: "Thunder", hex: "#3D3A3D", relatedTags: [.adventurous]),
//    Color(name: "Thunder", hex: "#231F20", relatedTags: [.elegant]),
    Color(name: "Violet Thunder", hex: "#3E2838", relatedTags: [.feminine, .elegant]),
    Color(name: "Timber Green", hex: "#102526", relatedTags: [.masculine]),
//    Color(name: "Tobacco Brown", hex: "#73543F", relatedTags: [.nature]),
//    Color(name: "Tower Gray", hex: "#A4BDBE", relatedTags: [.modern]),
//    Color(name: "Trout", hex: "#4C5162", relatedTags: [.adventurous]),
//    Color(name: "Tulip Tree", hex: "#E99F4C", relatedTags: [.feminine]),
    Color(name: "Tundora", hex: "#4C4C4C", relatedTags: [.feminine]),
    Color(name: "Turquoise Blue", hex: "#65E4E7", relatedTags: [.relaxing]),
    Color(name: "Verdun Green", hex: "#486B00", relatedTags: [.nature]),
//    Color(name: "Walnut", hex: "#7A431D", relatedTags: [.elegant]),
    Color(name: "Wedgewood", hex: "#47809A", relatedTags: [.relaxing]),
    Color(name: "White", hex: "#FFFFFF", relatedTags: [.relaxing, .elegant]),
//    Color(name: "Wild Sand", hex: "#F6F6F6", relatedTags: [.modern]),
    Color(name: "Yellow Metal", hex: "#785F37", relatedTags: [.elegant]),
    Color(name: "Zeus", hex: "#181510", relatedTags: [.elegant])
  ]

}
